
const DRAFT_KEY='reductCareerDraftV1';
const DB_NAME='reductCareerFiles'; const DB_STORE='files';
const form=document.getElementById('applicationForm');
const roleEl=document.getElementById('role'); const skillGrid=document.getElementById('skillGrid');
const saveIndicator=document.getElementById('saveIndicator'); const saveText=document.getElementById('saveText');
const languageList=document.getElementById('languageList'); const careerList=document.getElementById('careerList');
const photoInput=document.getElementById('photoInput'); const photoPreview=document.getElementById('photoPreview'); const photoMeta=document.getElementById('photoMeta');
let languages=[]; let careers=[]; let photoRecord=null; let saveTimer=null;
const ROLE_SKILLS={
 '영업':['B2B 신규영업','견적·제안서 작성','고객 커뮤니케이션','제조·기술 이해','영업 파이프라인 관리'],
 '영업관리':['견적·수주 관리','고객·납기 대응','매출·원가 관리','문서·데이터 관리','ERP·Excel 활용'],
 '하드웨어 개발':['회로 설계','PCB 설계·Layout','MCU·Sensor Interface','Power Management','디버깅·계측'],
 '펌웨어 개발':['C/C++','MCU Firmware','RTOS·Task 설계','UART·I2C·SPI·CAN','BLE·Wi-Fi·통신 디버깅'],
 'SW 개발':['Frontend/Web','Backend/API','Database','Git·협업개발','배포·운영·디버깅'],
 '마케팅':['콘텐츠 기획·제작','SEO·SEM','퍼포먼스 마케팅','데이터 분석','B2B·기술 마케팅']
};
const LEVELS=[['0','경험 없음'],['1','기초'],['2','실무 가능'],['3','독립 수행']];
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(DB_STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function idbSet(key,val){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(val,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function idbGet(key){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readonly');const r=tx.objectStore(DB_STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbDel(key){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function staticDraft(){const out={}; form.querySelectorAll('input[name],select[name],textarea[name]').forEach(el=>{if(el.type!=='file') out[el.name]=el.value}); out.privacyConsent=document.getElementById('privacyConsent').checked; out.languages=languages; out.careers=careers; out.skills=getSkills(); return out}
function scheduleSave(){saveIndicator.classList.remove('saved');saveText.textContent='저장 중…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>{localStorage.setItem(DRAFT_KEY,JSON.stringify(staticDraft()));saveIndicator.classList.add('saved');saveText.textContent='자동 저장됨';},280)}
function getSkills(){const x={};skillGrid.querySelectorAll('select[data-skill]').forEach(s=>x[s.dataset.skill]=Number(s.value||0));return x}
function renderSkills(saved={}){const role=roleEl.value; if(!ROLE_SKILLS[role]){skillGrid.innerHTML='<div class="privacy-box">먼저 기본정보에서 지원 분야를 선택해 주세요.</div>';return} skillGrid.innerHTML=ROLE_SKILLS[role].map(k=>`<div class="skill-row"><strong>${esc(k)}</strong><select data-skill="${esc(k)}">${LEVELS.map(([v,l])=>`<option value="${v}" ${Number(saved[k])===Number(v)?'selected':''}>${l}</option>`).join('')}</select></div>`).join('');skillGrid.querySelectorAll('select').forEach(x=>x.addEventListener('change',scheduleSave))}
function renderLanguages(){languageList.innerHTML=languages.map((x,i)=>`<div class="repeat-card"><div class="repeat-head"><strong>외국어 ${i+1}</strong><button class="remove-btn" type="button" data-remove-lang="${i}">삭제</button></div><div class="field-grid three"><div class="field"><label>언어</label><input data-lang="name" data-i="${i}" value="${esc(x.name||'')}"></div><div class="field"><label>시험/점수</label><input data-lang="score" data-i="${i}" value="${esc(x.score||'')}" placeholder="예: TOEIC 900"></div><div class="field"><label>회화 수준</label><select data-lang="level" data-i="${i}"><option value="">선택</option>${['Native','Fluent','Business','Conversational','Basic'].map(v=>`<option ${x.level===v?'selected':''}>${v}</option>`).join('')}</select></div></div></div>`).join(''); languageList.querySelectorAll('[data-lang]').forEach(el=>el.addEventListener('input',e=>{languages[+e.target.dataset.i][e.target.dataset.lang]=e.target.value;scheduleSave()})); languageList.querySelectorAll('[data-remove-lang]').forEach(b=>b.onclick=()=>{languages.splice(+b.dataset.removeLang,1);renderLanguages();scheduleSave()})}
function renderCareers(){careerList.innerHTML=careers.map((x,i)=>`<div class="repeat-card"><div class="repeat-head"><strong>경력 ${i+1}</strong><button class="remove-btn" type="button" data-remove-career="${i}">삭제</button></div><div class="field-grid three"><div class="field"><label>업체명</label><input data-career="company" data-i="${i}" value="${esc(x.company||'')}"></div><div class="field"><label>직급</label><input data-career="position" data-i="${i}" value="${esc(x.position||'')}"></div><div class="field"><label>연봉</label><input data-career="salary" data-i="${i}" value="${esc(x.salary||'')}"></div><div class="field"><label>입사일</label><input type="date" data-career="start" data-i="${i}" value="${esc(x.start||'')}"></div><div class="field"><label>퇴사일</label><input type="date" data-career="end" data-i="${i}" value="${esc(x.end||'')}"></div><div class="field"><label>재직상태</label><select data-career="current" data-i="${i}"><option value="">선택</option><option value="재직중" ${x.current==='재직중'?'selected':''}>재직중</option><option value="퇴사" ${x.current==='퇴사'?'selected':''}>퇴사</option></select></div><div class="field full"><label>주요업무</label><textarea data-career="duties" data-i="${i}" style="min-height:100px">${esc(x.duties||'')}</textarea></div></div></div>`).join(''); careerList.querySelectorAll('[data-career]').forEach(el=>el.addEventListener('input',e=>{careers[+e.target.dataset.i][e.target.dataset.career]=e.target.value;scheduleSave()}));careerList.querySelectorAll('[data-remove-career]').forEach(b=>b.onclick=()=>{careers.splice(+b.dataset.removeCareer,1);renderCareers();scheduleSave()})}
function monthsBetween(a,b){if(!a)return 0;const s=new Date(a),e=b?new Date(b):new Date();if(isNaN(s)||isNaN(e))return 0;return Math.max(0,(e.getFullYear()-s.getFullYear())*12+e.getMonth()-s.getMonth())}
function suitability(){const skills=getSkills();const vals=Object.values(skills);const skillAvg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;const skillScore=Math.round(skillAvg/3*60);let months=0;careers.forEach(c=>months+=monthsBetween(c.start,c.current==='재직중'?'':c.end));const years=months/12;const expScore=Math.round(Math.min(years/5,1)*20);const texts=['selfIntro','aspiration','qCrisis','qStress','qPeople'].map(id=>(document.getElementById(id).value||'').trim());const narrativeAvg=texts.reduce((s,t)=>s+Math.min(t.length/350,1),0)/texts.length;const narrativeScore=Math.round(narrativeAvg*20);const total=Math.min(100,skillScore+expScore+narrativeScore);let band=total>=85?'높음':total>=70?'검토 우선':total>=55?'보통':'추가 검토 필요';const top=Object.entries(skills).sort((a,b)=>b[1]-a[1]).slice(0,2).filter(x=>x[1]>0).map(x=>x[0]).join(', ')||'자기평가 정보 부족';return{total,band,skillScore,expScore,narrativeScore,years:years.toFixed(1),top}}
function langSummary(){return languages.length?languages.map((x,i)=>`${i+1}. ${x.name||'-'} / ${x.score||'점수 없음'} / ${x.level||'수준 미입력'}`).join('\n'):'없음'}
function careerSummary(){return careers.length?careers.map((x,i)=>`${i+1}. ${x.company||'-'} | ${x.position||'-'} | ${x.start||'-'} ~ ${x.current==='재직중'?'재직중':(x.end||'-')} | 연봉 ${x.salary||'-'}\n주요업무: ${x.duties||'-'}`).join('\n\n'):'신입 또는 경력 미입력'}
async function restore(){let d={};try{d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'{}')}catch{};Object.entries(d).forEach(([k,v])=>{const el=form.elements[k];if(el&&typeof v!=='object')el.value=v});if(d.privacyConsent)document.getElementById('privacyConsent').checked=true;languages=Array.isArray(d.languages)?d.languages:[];careers=Array.isArray(d.careers)?d.careers:[];renderLanguages();renderCareers();renderSkills(d.skills||{});try{photoRecord=await idbGet('photo');if(photoRecord?.blob){const restoredFile=new File([photoRecord.blob],photoRecord.name,{type:photoRecord.type||photoRecord.blob.type});try{const dt=new DataTransfer();dt.items.add(restoredFile);photoInput.files=dt.files}catch(e){}const url=URL.createObjectURL(photoRecord.blob);photoPreview.innerHTML=`<img src="${url}" alt="증명사진 미리보기">`;photoMeta.textContent=`저장된 사진: ${photoRecord.name} · 적합도 산정에는 사용하지 않습니다.`}}catch(e){};saveText.textContent=localStorage.getItem(DRAFT_KEY)?'저장된 지원서를 불러왔습니다':'자동 저장 준비됨'}
form.addEventListener('input',scheduleSave); form.addEventListener('change',scheduleSave); roleEl.addEventListener('change',()=>{renderSkills();scheduleSave()});
document.getElementById('addLanguage').onclick=()=>{languages.push({name:'',score:'',level:''});renderLanguages();scheduleSave()}; document.getElementById('addCareer').onclick=()=>{careers.push({company:'',position:'',salary:'',start:'',end:'',current:'',duties:''});renderCareers();scheduleSave()};
photoInput.addEventListener('change',async()=>{const f=photoInput.files[0];if(!f)return;if(f.size>5*1024*1024){alert('사진은 5MB 이하로 선택해 주세요.');photoInput.value='';return}photoRecord={name:f.name,type:f.type,blob:f};await idbSet('photo',photoRecord);photoPreview.innerHTML=`<img src="${URL.createObjectURL(f)}" alt="증명사진 미리보기">`;photoMeta.textContent=`${f.name} · ${(f.size/1024/1024).toFixed(1)}MB · 자동 저장됨`;scheduleSave()});
function setHidden(name,value){let el=form.querySelector(`input[type="hidden"][data-generated="1"][name="${CSS.escape(name)}"]`);if(!el){el=document.createElement('input');el.type='hidden';el.name=name;el.dataset.generated='1';form.appendChild(el)}el.value=value}
form.addEventListener('submit',async e=>{const status=document.getElementById('submitStatus'),btn=document.getElementById('submitBtn');if(!form.checkValidity()){e.preventDefault();form.reportValidity();status.textContent='필수 입력 항목을 확인해 주세요.';status.className='submit-status error';return}const fit=suitability();setHidden('_subject',`[REDUCT 입사지원] ${roleEl.value} / ${document.getElementById('name').value}`);setHidden('지원 직무',roleEl.value);setHidden('이름',document.getElementById('name').value);setHidden('연락처',document.getElementById('phone').value);setHidden('개인 이메일',document.getElementById('email').value);setHidden('희망연봉',document.getElementById('desiredSalary').value||'-');setHidden('입사 가능일',document.getElementById('availableDate').value||'-');setHidden('주소',document.getElementById('address').value||'-');setHidden('최종학력',`${document.getElementById('eduLevel').value||'-'} / ${document.getElementById('eduSchool').value||'-'} / ${document.getElementById('eduMajor').value||'-'} / ${document.getElementById('eduStatus').value||'-'} / ${document.getElementById('eduStart').value||'-'} ~ ${document.getElementById('eduEnd').value||'-'}`);setHidden('외국어',langSummary());setHidden('경력',careerSummary());setHidden('직무역량 자기평가',Object.entries(getSkills()).map(([k,v])=>`${k}: ${LEVELS.find(x=>+x[0]===+v)?.[1]||v}`).join(' / '));setHidden('자기소개',document.getElementById('selfIntro').value);setHidden('입사 후 포부',document.getElementById('aspiration').value);setHidden('Q1 위기대처',document.getElementById('qCrisis').value);setHidden('Q2 스트레스·우선순위',document.getElementById('qStress').value);setHidden('Q3 관계·갈등관리',document.getElementById('qPeople').value);setHidden('사전 직무 적합도',`${fit.total}/100 (${fit.band})`);setHidden('적합도 산정 근거',`직무역량 ${fit.skillScore}/60 · 경력 ${fit.expScore}/20 (${fit.years}년) · 서술응답 완성도 ${fit.narrativeScore}/20 · 자기평가 상위역량: ${fit.top}`);setHidden('평가 안내','지원자가 입력한 직무 관련 역량·경력·서술응답만으로 계산한 사전 참고점수입니다. 사진, 주소, 학력연도, 외국어 등은 점수 산정에 사용하지 않았으며 최종 채용판단은 면접과 별도 검토가 필요합니다.');if(photoRecord?.blob && !photoInput.files.length){try{const f=new File([photoRecord.blob],photoRecord.name,{type:photoRecord.type||photoRecord.blob.type});const dt=new DataTransfer();dt.items.add(f);photoInput.files=dt.files}catch(err){e.preventDefault();status.textContent='저장된 증명사진을 자동 첨부하지 못했습니다. 사진을 다시 선택한 뒤 제출해 주세요.';status.className='submit-status error';return}}btn.disabled=true;btn.textContent='제출 중…';status.textContent='지원서를 전송하고 있습니다.';status.className='submit-status'});
restore();
